### ISSUE TITLE
Your code has an issue, but require('chrome') works

### ISSUE THREAD

**Issue by Noitidart** [AlJohnson/SDKExperiments#1]
Hi Al,
I didn't debug your stuff. But I tried it and got the same error. So I created a new project with just `require('chrome')` and `Cu.import` and it works here's a vid for you -

https://www.youtube.com/watch?v=ZxQyCo9iTsU

**Comment by Noitidart** [comment]
Also don't use FileUtils.jsm use OS.File.js - https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.File_for_the_main_thread

That's the recommended way. I use it for everything. It works especially well from workers too.

**Comment by AlJohnson** [comment]
Ah, thanks, I noticed my dumb mistake ;)

**Comment by Noitidart** [comment]
Cool man! :) Seriously consier OS.File instead it is absolutely superb!

**Comment by AlJohnson** [comment]
Oh, I will!  I noticed you recommending it elsewhere while I was doing a survey of all the storage APIs available.  But, currently, I'm trying to see if I can get a list of drives or removable storage devices and a stackoverflow page used FileUtils.  Did you do any work on OS.File?

**Comment by AlJohnson** [comment]
And do you know if OS.File will allow me to get that list of devices I mentioned?

**Comment by Noitidart** [comment]
Interesting how did you get the list of drives with `FileUtils`? I'll then give you the `OS.File` way.

**Comment by AlJohnson** [comment]
I'm about to try this: http://stackoverflow.com/questions/26973645/list-all-drives-using-firefox-addon-sdk
